import type { Metadata } from "next";
import {Prompt } from "next/font/google";
import "./globals.css";

const prompt= Prompt({
  subsets: ["thai" ,"latin"],
  weight: ["400", "700"],
  variable: "--font-prompt",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by Luttapon",
  keywords: ["Tracker", "Health", "Food", "Restaurant"], 
  icons: {
    icon: "/vercel.svg",

  },
  authors: [
    { name: "Luttapon" ,
      url: "https://luttapon.dev"
    },

  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={prompt.className}
      >
        {children}
      </body>
    </html>
  );
}
